// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/gm/server/model/model.proto

package com.gm.server.model;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FriendOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 id = 1;
    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    // required .com.gm.server.model.Friend.Type type = 2;
    /**
     * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
     */
    com.gm.server.model.Model.Friend.Type getType();
  }
  /**
   * Protobuf type {@code com.gm.server.model.Friend}
   */
  public static final class Friend extends
      com.google.protobuf.GeneratedMessage
      implements FriendOrBuilder {
    // Use Friend.newBuilder() to construct.
    private Friend(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Friend(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Friend defaultInstance;
    public static Friend getDefaultInstance() {
      return defaultInstance;
    }

    public Friend getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Friend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.gm.server.model.Model.Friend.Type value = com.gm.server.model.Model.Friend.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.server.model.Model.internal_static_com_gm_server_model_Friend_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.server.model.Model.internal_static_com_gm_server_model_Friend_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.server.model.Model.Friend.class, com.gm.server.model.Model.Friend.Builder.class);
    }

    public static com.google.protobuf.Parser<Friend> PARSER =
        new com.google.protobuf.AbstractParser<Friend>() {
      public Friend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Friend(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Friend> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.gm.server.model.Friend.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONFIRMED = 0;</code>
       */
      CONFIRMED(0, 0),
      /**
       * <code>ADDED = 1;</code>
       */
      ADDED(1, 1),
      /**
       * <code>WAIT_MY_CONFIRM = 2;</code>
       */
      WAIT_MY_CONFIRM(2, 2),
      /**
       * <code>INVITED = 3;</code>
       */
      INVITED(3, 3),
      /**
       * <code>WATCHED = 4;</code>
       */
      WATCHED(4, 4),
      /**
       * <code>BLOCKED = 5;</code>
       */
      BLOCKED(5, 5),
      ;

      /**
       * <code>CONFIRMED = 0;</code>
       */
      public static final int CONFIRMED_VALUE = 0;
      /**
       * <code>ADDED = 1;</code>
       */
      public static final int ADDED_VALUE = 1;
      /**
       * <code>WAIT_MY_CONFIRM = 2;</code>
       */
      public static final int WAIT_MY_CONFIRM_VALUE = 2;
      /**
       * <code>INVITED = 3;</code>
       */
      public static final int INVITED_VALUE = 3;
      /**
       * <code>WATCHED = 4;</code>
       */
      public static final int WATCHED_VALUE = 4;
      /**
       * <code>BLOCKED = 5;</code>
       */
      public static final int BLOCKED_VALUE = 5;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return CONFIRMED;
          case 1: return ADDED;
          case 2: return WAIT_MY_CONFIRM;
          case 3: return INVITED;
          case 4: return WATCHED;
          case 5: return BLOCKED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.gm.server.model.Model.Friend.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.gm.server.model.Friend.Type)
    }

    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // required .com.gm.server.model.Friend.Type type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private com.gm.server.model.Model.Friend.Type type_;
    /**
     * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
     */
    public com.gm.server.model.Model.Friend.Type getType() {
      return type_;
    }

    private void initFields() {
      id_ = 0L;
      type_ = com.gm.server.model.Model.Friend.Type.CONFIRMED;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gm.server.model.Model.Friend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gm.server.model.Model.Friend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gm.server.model.Model.Friend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gm.server.model.Model.Friend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gm.server.model.Model.Friend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gm.server.model.Model.Friend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gm.server.model.Model.Friend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gm.server.model.Friend}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gm.server.model.Model.FriendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gm.server.model.Model.internal_static_com_gm_server_model_Friend_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gm.server.model.Model.internal_static_com_gm_server_model_Friend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gm.server.model.Model.Friend.class, com.gm.server.model.Model.Friend.Builder.class);
      }

      // Construct using com.gm.server.model.Model.Friend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.gm.server.model.Model.Friend.Type.CONFIRMED;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gm.server.model.Model.internal_static_com_gm_server_model_Friend_descriptor;
      }

      public com.gm.server.model.Model.Friend getDefaultInstanceForType() {
        return com.gm.server.model.Model.Friend.getDefaultInstance();
      }

      public com.gm.server.model.Model.Friend build() {
        com.gm.server.model.Model.Friend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gm.server.model.Model.Friend buildPartial() {
        com.gm.server.model.Model.Friend result = new com.gm.server.model.Model.Friend(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gm.server.model.Model.Friend) {
          return mergeFrom((com.gm.server.model.Model.Friend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gm.server.model.Model.Friend other) {
        if (other == com.gm.server.model.Model.Friend.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gm.server.model.Model.Friend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gm.server.model.Model.Friend) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 id = 1;
      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required .com.gm.server.model.Friend.Type type = 2;
      private com.gm.server.model.Model.Friend.Type type_ = com.gm.server.model.Model.Friend.Type.CONFIRMED;
      /**
       * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
       */
      public com.gm.server.model.Model.Friend.Type getType() {
        return type_;
      }
      /**
       * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
       */
      public Builder setType(com.gm.server.model.Model.Friend.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.gm.server.model.Friend.Type type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.gm.server.model.Model.Friend.Type.CONFIRMED;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gm.server.model.Friend)
    }

    static {
      defaultInstance = new Friend(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gm.server.model.Friend)
  }

  public interface FriendshipOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.gm.server.model.Friend friend = 1;
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    java.util.List<com.gm.server.model.Model.Friend> 
        getFriendList();
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    com.gm.server.model.Model.Friend getFriend(int index);
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    int getFriendCount();
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    java.util.List<? extends com.gm.server.model.Model.FriendOrBuilder> 
        getFriendOrBuilderList();
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    com.gm.server.model.Model.FriendOrBuilder getFriendOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.gm.server.model.Friendship}
   */
  public static final class Friendship extends
      com.google.protobuf.GeneratedMessage
      implements FriendshipOrBuilder {
    // Use Friendship.newBuilder() to construct.
    private Friendship(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Friendship(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Friendship defaultInstance;
    public static Friendship getDefaultInstance() {
      return defaultInstance;
    }

    public Friendship getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Friendship(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                friend_ = new java.util.ArrayList<com.gm.server.model.Model.Friend>();
                mutable_bitField0_ |= 0x00000001;
              }
              friend_.add(input.readMessage(com.gm.server.model.Model.Friend.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          friend_ = java.util.Collections.unmodifiableList(friend_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.server.model.Model.internal_static_com_gm_server_model_Friendship_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.server.model.Model.internal_static_com_gm_server_model_Friendship_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.server.model.Model.Friendship.class, com.gm.server.model.Model.Friendship.Builder.class);
    }

    public static com.google.protobuf.Parser<Friendship> PARSER =
        new com.google.protobuf.AbstractParser<Friendship>() {
      public Friendship parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Friendship(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Friendship> getParserForType() {
      return PARSER;
    }

    // repeated .com.gm.server.model.Friend friend = 1;
    public static final int FRIEND_FIELD_NUMBER = 1;
    private java.util.List<com.gm.server.model.Model.Friend> friend_;
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    public java.util.List<com.gm.server.model.Model.Friend> getFriendList() {
      return friend_;
    }
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    public java.util.List<? extends com.gm.server.model.Model.FriendOrBuilder> 
        getFriendOrBuilderList() {
      return friend_;
    }
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    public int getFriendCount() {
      return friend_.size();
    }
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    public com.gm.server.model.Model.Friend getFriend(int index) {
      return friend_.get(index);
    }
    /**
     * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
     */
    public com.gm.server.model.Model.FriendOrBuilder getFriendOrBuilder(
        int index) {
      return friend_.get(index);
    }

    private void initFields() {
      friend_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getFriendCount(); i++) {
        if (!getFriend(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < friend_.size(); i++) {
        output.writeMessage(1, friend_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < friend_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, friend_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gm.server.model.Model.Friendship parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gm.server.model.Model.Friendship parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friendship parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gm.server.model.Model.Friendship parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friendship parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gm.server.model.Model.Friendship parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friendship parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gm.server.model.Model.Friendship parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gm.server.model.Model.Friendship parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gm.server.model.Model.Friendship parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gm.server.model.Model.Friendship prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gm.server.model.Friendship}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gm.server.model.Model.FriendshipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gm.server.model.Model.internal_static_com_gm_server_model_Friendship_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gm.server.model.Model.internal_static_com_gm_server_model_Friendship_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gm.server.model.Model.Friendship.class, com.gm.server.model.Model.Friendship.Builder.class);
      }

      // Construct using com.gm.server.model.Model.Friendship.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFriendFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (friendBuilder_ == null) {
          friend_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          friendBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gm.server.model.Model.internal_static_com_gm_server_model_Friendship_descriptor;
      }

      public com.gm.server.model.Model.Friendship getDefaultInstanceForType() {
        return com.gm.server.model.Model.Friendship.getDefaultInstance();
      }

      public com.gm.server.model.Model.Friendship build() {
        com.gm.server.model.Model.Friendship result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gm.server.model.Model.Friendship buildPartial() {
        com.gm.server.model.Model.Friendship result = new com.gm.server.model.Model.Friendship(this);
        int from_bitField0_ = bitField0_;
        if (friendBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            friend_ = java.util.Collections.unmodifiableList(friend_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.friend_ = friend_;
        } else {
          result.friend_ = friendBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gm.server.model.Model.Friendship) {
          return mergeFrom((com.gm.server.model.Model.Friendship)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gm.server.model.Model.Friendship other) {
        if (other == com.gm.server.model.Model.Friendship.getDefaultInstance()) return this;
        if (friendBuilder_ == null) {
          if (!other.friend_.isEmpty()) {
            if (friend_.isEmpty()) {
              friend_ = other.friend_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFriendIsMutable();
              friend_.addAll(other.friend_);
            }
            onChanged();
          }
        } else {
          if (!other.friend_.isEmpty()) {
            if (friendBuilder_.isEmpty()) {
              friendBuilder_.dispose();
              friendBuilder_ = null;
              friend_ = other.friend_;
              bitField0_ = (bitField0_ & ~0x00000001);
              friendBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFriendFieldBuilder() : null;
            } else {
              friendBuilder_.addAllMessages(other.friend_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFriendCount(); i++) {
          if (!getFriend(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gm.server.model.Model.Friendship parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gm.server.model.Model.Friendship) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.gm.server.model.Friend friend = 1;
      private java.util.List<com.gm.server.model.Model.Friend> friend_ =
        java.util.Collections.emptyList();
      private void ensureFriendIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          friend_ = new java.util.ArrayList<com.gm.server.model.Model.Friend>(friend_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.gm.server.model.Model.Friend, com.gm.server.model.Model.Friend.Builder, com.gm.server.model.Model.FriendOrBuilder> friendBuilder_;

      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public java.util.List<com.gm.server.model.Model.Friend> getFriendList() {
        if (friendBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friend_);
        } else {
          return friendBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public int getFriendCount() {
        if (friendBuilder_ == null) {
          return friend_.size();
        } else {
          return friendBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public com.gm.server.model.Model.Friend getFriend(int index) {
        if (friendBuilder_ == null) {
          return friend_.get(index);
        } else {
          return friendBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder setFriend(
          int index, com.gm.server.model.Model.Friend value) {
        if (friendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendIsMutable();
          friend_.set(index, value);
          onChanged();
        } else {
          friendBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder setFriend(
          int index, com.gm.server.model.Model.Friend.Builder builderForValue) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder addFriend(com.gm.server.model.Model.Friend value) {
        if (friendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendIsMutable();
          friend_.add(value);
          onChanged();
        } else {
          friendBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder addFriend(
          int index, com.gm.server.model.Model.Friend value) {
        if (friendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendIsMutable();
          friend_.add(index, value);
          onChanged();
        } else {
          friendBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder addFriend(
          com.gm.server.model.Model.Friend.Builder builderForValue) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.add(builderForValue.build());
          onChanged();
        } else {
          friendBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder addFriend(
          int index, com.gm.server.model.Model.Friend.Builder builderForValue) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder addAllFriend(
          java.lang.Iterable<? extends com.gm.server.model.Model.Friend> values) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          super.addAll(values, friend_);
          onChanged();
        } else {
          friendBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder clearFriend() {
        if (friendBuilder_ == null) {
          friend_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          friendBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public Builder removeFriend(int index) {
        if (friendBuilder_ == null) {
          ensureFriendIsMutable();
          friend_.remove(index);
          onChanged();
        } else {
          friendBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public com.gm.server.model.Model.Friend.Builder getFriendBuilder(
          int index) {
        return getFriendFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public com.gm.server.model.Model.FriendOrBuilder getFriendOrBuilder(
          int index) {
        if (friendBuilder_ == null) {
          return friend_.get(index);  } else {
          return friendBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public java.util.List<? extends com.gm.server.model.Model.FriendOrBuilder> 
           getFriendOrBuilderList() {
        if (friendBuilder_ != null) {
          return friendBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friend_);
        }
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public com.gm.server.model.Model.Friend.Builder addFriendBuilder() {
        return getFriendFieldBuilder().addBuilder(
            com.gm.server.model.Model.Friend.getDefaultInstance());
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public com.gm.server.model.Model.Friend.Builder addFriendBuilder(
          int index) {
        return getFriendFieldBuilder().addBuilder(
            index, com.gm.server.model.Model.Friend.getDefaultInstance());
      }
      /**
       * <code>repeated .com.gm.server.model.Friend friend = 1;</code>
       */
      public java.util.List<com.gm.server.model.Model.Friend.Builder> 
           getFriendBuilderList() {
        return getFriendFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.gm.server.model.Model.Friend, com.gm.server.model.Model.Friend.Builder, com.gm.server.model.Model.FriendOrBuilder> 
          getFriendFieldBuilder() {
        if (friendBuilder_ == null) {
          friendBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.gm.server.model.Model.Friend, com.gm.server.model.Model.Friend.Builder, com.gm.server.model.Model.FriendOrBuilder>(
                  friend_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          friend_ = null;
        }
        return friendBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.gm.server.model.Friendship)
    }

    static {
      defaultInstance = new Friendship(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gm.server.model.Friendship)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gm_server_model_Friend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gm_server_model_Friend_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gm_server_model_Friendship_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gm_server_model_Friendship_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)main/java/com/gm/server/model/model.pr" +
      "oto\022\023com.gm.server.model\"\242\001\n\006Friend\022\n\n\002i" +
      "d\030\001 \002(\003\022.\n\004type\030\002 \002(\0162 .com.gm.server.mo" +
      "del.Friend.Type\"\\\n\004Type\022\r\n\tCONFIRMED\020\000\022\t" +
      "\n\005ADDED\020\001\022\023\n\017WAIT_MY_CONFIRM\020\002\022\013\n\007INVITE" +
      "D\020\003\022\013\n\007WATCHED\020\004\022\013\n\007BLOCKED\020\005\"9\n\nFriends" +
      "hip\022+\n\006friend\030\001 \003(\0132\033.com.gm.server.mode" +
      "l.Friend"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_gm_server_model_Friend_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_gm_server_model_Friend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gm_server_model_Friend_descriptor,
              new java.lang.String[] { "Id", "Type", });
          internal_static_com_gm_server_model_Friendship_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_gm_server_model_Friendship_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gm_server_model_Friendship_descriptor,
              new java.lang.String[] { "Friend", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
