// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/java/com/gm/server/model/test.proto

package com.gm.server.model;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthorListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string author = 1;
    /**
     * <code>repeated string author = 1;</code>
     */
    java.util.List<java.lang.String>
    getAuthorList();
    /**
     * <code>repeated string author = 1;</code>
     */
    int getAuthorCount();
    /**
     * <code>repeated string author = 1;</code>
     */
    java.lang.String getAuthor(int index);
    /**
     * <code>repeated string author = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes(int index);
  }
  /**
   * Protobuf type {@code com.gm.server.model.AuthorList}
   */
  public static final class AuthorList extends
      com.google.protobuf.GeneratedMessage
      implements AuthorListOrBuilder {
    // Use AuthorList.newBuilder() to construct.
    private AuthorList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthorList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthorList defaultInstance;
    public static AuthorList getDefaultInstance() {
      return defaultInstance;
    }

    public AuthorList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthorList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                author_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              author_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          author_ = new com.google.protobuf.UnmodifiableLazyStringList(author_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.server.model.Test.internal_static_com_gm_server_model_AuthorList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.server.model.Test.internal_static_com_gm_server_model_AuthorList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.server.model.Test.AuthorList.class, com.gm.server.model.Test.AuthorList.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthorList> PARSER =
        new com.google.protobuf.AbstractParser<AuthorList>() {
      public AuthorList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthorList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthorList> getParserForType() {
      return PARSER;
    }

    // repeated string author = 1;
    public static final int AUTHOR_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList author_;
    /**
     * <code>repeated string author = 1;</code>
     */
    public java.util.List<java.lang.String>
        getAuthorList() {
      return author_;
    }
    /**
     * <code>repeated string author = 1;</code>
     */
    public int getAuthorCount() {
      return author_.size();
    }
    /**
     * <code>repeated string author = 1;</code>
     */
    public java.lang.String getAuthor(int index) {
      return author_.get(index);
    }
    /**
     * <code>repeated string author = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes(int index) {
      return author_.getByteString(index);
    }

    private void initFields() {
      author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < author_.size(); i++) {
        output.writeBytes(1, author_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < author_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(author_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAuthorList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gm.server.model.Test.AuthorList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gm.server.model.Test.AuthorList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gm.server.model.Test.AuthorList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gm.server.model.Test.AuthorList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gm.server.model.Test.AuthorList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gm.server.model.Test.AuthorList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gm.server.model.Test.AuthorList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gm.server.model.Test.AuthorList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gm.server.model.Test.AuthorList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gm.server.model.Test.AuthorList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gm.server.model.Test.AuthorList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gm.server.model.AuthorList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gm.server.model.Test.AuthorListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gm.server.model.Test.internal_static_com_gm_server_model_AuthorList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gm.server.model.Test.internal_static_com_gm_server_model_AuthorList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gm.server.model.Test.AuthorList.class, com.gm.server.model.Test.AuthorList.Builder.class);
      }

      // Construct using com.gm.server.model.Test.AuthorList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gm.server.model.Test.internal_static_com_gm_server_model_AuthorList_descriptor;
      }

      public com.gm.server.model.Test.AuthorList getDefaultInstanceForType() {
        return com.gm.server.model.Test.AuthorList.getDefaultInstance();
      }

      public com.gm.server.model.Test.AuthorList build() {
        com.gm.server.model.Test.AuthorList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gm.server.model.Test.AuthorList buildPartial() {
        com.gm.server.model.Test.AuthorList result = new com.gm.server.model.Test.AuthorList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          author_ = new com.google.protobuf.UnmodifiableLazyStringList(
              author_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.author_ = author_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gm.server.model.Test.AuthorList) {
          return mergeFrom((com.gm.server.model.Test.AuthorList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gm.server.model.Test.AuthorList other) {
        if (other == com.gm.server.model.Test.AuthorList.getDefaultInstance()) return this;
        if (!other.author_.isEmpty()) {
          if (author_.isEmpty()) {
            author_ = other.author_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAuthorIsMutable();
            author_.addAll(other.author_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gm.server.model.Test.AuthorList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gm.server.model.Test.AuthorList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string author = 1;
      private com.google.protobuf.LazyStringList author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAuthorIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          author_ = new com.google.protobuf.LazyStringArrayList(author_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public java.util.List<java.lang.String>
          getAuthorList() {
        return java.util.Collections.unmodifiableList(author_);
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public int getAuthorCount() {
        return author_.size();
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public java.lang.String getAuthor(int index) {
        return author_.get(index);
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes(int index) {
        return author_.getByteString(index);
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public Builder setAuthor(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIsMutable();
        author_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public Builder addAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIsMutable();
        author_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public Builder addAllAuthor(
          java.lang.Iterable<java.lang.String> values) {
        ensureAuthorIsMutable();
        super.addAll(values, author_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public Builder clearAuthor() {
        author_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string author = 1;</code>
       */
      public Builder addAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthorIsMutable();
        author_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.gm.server.model.AuthorList)
    }

    static {
      defaultInstance = new AuthorList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.gm.server.model.AuthorList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gm_server_model_AuthorList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_gm_server_model_AuthorList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(test/java/com/gm/server/model/test.pro" +
      "to\022\023com.gm.server.model\"\034\n\nAuthorList\022\016\n" +
      "\006author\030\001 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_gm_server_model_AuthorList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_gm_server_model_AuthorList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_gm_server_model_AuthorList_descriptor,
              new java.lang.String[] { "Author", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
